version: "3"

networks:
  local:

services:
  site:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./php/src:/php/src
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - go-service
      - php-service
    networks:
      - local

  go-service:
    build:
      context: .
      dockerfile: go.dockerfile
    container_name: go-service
    restart: always
    ports:
      - "8000"
    networks:
      - local

  php-service:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php-service
    restart: always
    volumes:
      - ./php/src:/php/src
    ports:
      - "9000:9000"
    networks:
      - local
